print ("hello world")
print ("reflek menguasai 12 universe")
print ("jangan lupa untuk selalu bernafas")
print ("reflek menguasai kawasan benua eropa")
print ("minimal mandi")
print ("pmsatir hanmdal)
print ("teruslah mengocok patrick")
print ("harga diri berapa harganya?")
print ("ahh bingung")
print ("alok hamil")